---
deployment:
  tasks:
    - export DEPLOYPATH=/home/legadoholding/public_html/funerzul
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R index.html styles.css app.js admin.js admin.html favicon.png logo.png uploads $DEPLOYPATH
