---
deployment:
  tasks:
    - export DEPLOYPATH=/home/legadoholding/public_html/funerzul
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp admin.js $DEPLOYPATH
    - /bin/cp admin.html $DEPLOYPATH
    - /bin/cp uploads $DEPLOYPATH
